-- Insertar códigos de marcación por país en la tabla tbDialingCodes (lista consolidada)
INSERT INTO tbDialingCodes (dialing_code, country_name) VALUES
('1', 'United States'),
('44', 'United Kingdom'),
('33', 'France'),
('49', 'Germany'),
('81', 'Japan'),
('86', 'China'),
('91', 'India'),
('52', 'Mexico'),
('34', 'Spain'),
('55', 'Brazil'),
('7', 'Russia'),
('61', 'Australia'),
('27', 'South Africa'),
('82', 'South Korea'),
('20', 'Egypt'),
('971', 'United Arab Emirates'),
('351', 'Portugal'),
('7', 'Kazakhstan'),
('62', 'Indonesia'),
('880', 'Bangladesh'),
('30', 'Greece'),
('54', 'Argentina'),
('506', 'Costa Rica'),
('507', 'Panama'),
('44', 'Ireland'),
('65', 'Singapore'),
('39', 'Italy'),
('81', 'South Sudan'),
('95', 'Myanmar'),
('230', 'Mauritius'),
('81', 'North Korea'),
('595', 'Paraguay'),
('263', 'Zimbabwe'),
('20', 'Morocco'),
('57', 'Colombia'),
('7', 'Uzbekistan'),
('351', 'Angola'),
('506', 'Honduras'),
('263', 'Zambia'),
('220', 'Gambia'),
('965', 'Kuwait'),
('856', 'Laos'),
('95', 'Nepal'),
('63', 'Philippines'),
('1', 'Canada'),
('82', 'Vietnam'),
('972', 'Israel'),
('66', 'Thailand'),
('263', 'Botswana'),
('967', 'Yemen'),
('256', 'Uganda'),
('251', 'Ethiopia'),
('34', 'Chile'),
('233', 'Ghana'),
('381', 'Serbia'),
('220', 'Senegal'),
('243', 'Congo (Kinshasa)'),
('242', 'Congo (Brazzaville)'),
('249', 'Sudan'),
('975', 'Bhutan'),
('974', 'Qatar'),
('967', 'Oman'),
('963', 'Syria'),
('960', 'Maldives'),
('675', 'Papua New Guinea'),
('51', 'Peru'),
('48', 'Poland'),
('40', 'Romania'),
('250', 'Rwanda'),
('290', 'Saint Helena'),
('1', 'Saint Kitts and Nevis'),
('1', 'Saint Lucia'),
('508', 'Saint Pierre and Miquelon'),
('1', 'Saint Vincent and the Grenadines'),
('685', 'Samoa'),
('378', 'San Marino'),
('239', 'Sao Tome and Principe'),
('966', 'Saudi Arabia'),
('248', 'Seychelles'),
('232', 'Sierra Leone'),
('1', 'Sint Maarten (Dutch part)'),
('421', 'Slovakia'),
('386', 'Slovenia'),
('677', 'Solomon Islands'),
('252', 'Somalia'),
('27', 'South Africa'),
('500', 'South Georgia and the South Sandwich Islands'),
('211', 'South Sudan'),
('34', 'Spain'),
('94', 'Sri Lanka'),
('249', 'Sudan'),
('597', 'Suriname'),
('47', 'Svalbard and Jan Mayen'),
('268', 'Swaziland'),
('46', 'Sweden'),
('41', 'Switzerland'),
('963', 'Syria'),
('992', 'Tajikistan'),
('255', 'Tanzania'),
('66', 'Thailand'),
('670', 'Timor-Leste'),
('228', 'Togo'),
('690', 'Tokelau'),
('676', 'Tonga'),
('1', 'Trinidad and Tobago'),
('216', 'Tunisia'),
('90', 'Turkey'),
('993', 'Turkmenistan'),
('1', 'Turks and Caicos Islands'),
('688', 'Tuvalu'),
('256', 'Uganda'),
('380', 'Ukraine'),
('971', 'United Arab Emirates'),
('44', 'United Kingdom'),
('1', 'United States'),
('598', 'Uruguay'),
('998', 'Uzbekistan'),
('678', 'Vanuatu'),
('58', 'Venezuela'),
('84', 'Vietnam'),
('681', 'Wallis and Futuna'),
('212', 'Western Sahara'),
('967', 'Yemen'),
('260', 'Zambia'),
('263', 'Zimbabwe'),
('358', 'Åland Islands');

INSERT INTO tbUsers (
    username,
    password,
    first_name,
    last_name,
    address,
    legal_representative_name,
    corporation_name,
    account_balance
) VALUES (
    'carrilloandresf',
    SHA2('1234felipe', 256),
    'Felipe',
    'Carrillo',
    'Calle 5 n 5-5',
    'Representante Legal',
    'Nombre de la Corporación',
    null
);

INSERT INTO tbUsers (
    username,
    password,
    first_name,
    last_name,
    address,
    legal_representative_name,
    corporation_name,
    account_balance
) VALUES (
    'jsierra',
    SHA2('1234jsierra', 256),
    'John',
    'Sierra',
    'Calle 5 n 5-5',
    'Representante Legal',
    'Nombre de la Corporación',
    null
);

INSERT INTO tbtransactiontypes (
    transaction_type, cost, price, user_id
) VALUES (
    'SMS', 8.00, 19.00, 1
), (
    'CALL', 12.00, 22.00, 1
), (
    'SMS', 8.00, 19.00, 2
), (
    'CALL', 12.00, 22.00, 2
);
